### ISSUE TITLE
DDoS attack

### ISSUE THREAD

**Issue by Coolkiddox** [m-obeid/POCOChat-Client-Desktop#2]
The website Is closed
![Screenshot_2022-11-13-17-45-48-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/116502667/201533448-639511c0-eefe-401a-ace3-17477525d960.jpg)

**Comment by m-obeid** [comment]
It works again. The servers were getting a system update, thats why it didn't work. closed
