### ISSUE TITLE
Hello - newlinersseries

### ISSUE THREAD

**Issue by upintheairsheep** [m-obeid/POCOChat-Client-Desktop#3]
Hello, I am newlinersseries on TikTok and I could get some help with a python improvements im making, its some updates for yt-dlp. https://github.com/upintheairsheep/ytdl-sheep Please fix the code and test it, and as i have been banned from yt-dlp for rapid issue making (Because I have OCD) and pull request it into the main yt-dlp repository.

**Comment by m-obeid** [comment]
Please don't send issues not related to POCOChat.
